name: Build Java Applications with GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub project
      uses: actions/checkout@v2
      with:
    - name: Setup JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}